### ISSUE TITLE
Aceitar padrão de placas do Mercosul ao editar informações de veículo

### ISSUE THREAD

**Issue by DamascenoRafael** [caronae/caronae-android#8]
Quando o usuário logado selecionar "menu > meu perfil > editar" deve ser possível inserir nas informações do veículo tanto uma placa com o padrão brasileiro (`AAA-1234`) como no padrão Mercosul (`AAA1A23`, sendo que as letras e números podem acontecer em qualquer ordem).

Atualmente a entrada da placa acontece com o auxílio da lib [InputMask](https://github.com/RedMadRobot/input-mask-android), porém como existem muitas combinações do padrão Mercosul a abordagem deve ser feita sem o auxílio dessa lib.

Ao salvar, a string da placa deve ser válida em uma das duas regex:
brazilianPlateRegex = `^[A-Z]{3}-[0-9]{4}$`
mercosulPlateRegex = `^(?=(?:.*[0-9]){3})(?=(?:.*[A-Z]){4})[A-Z0-9]{7}$`

**Comment by renanrhoden** [comment]
posso pegar?

**Comment by DamascenoRafael** [comment]
Claro @renanrhoden! Qualquer dúvida é só falar.

**Comment by renanrhoden** [comment]
@DamascenoRafael tenho uma é como testaria a solução dentro do app. Existe algum usuário de teste disponível?

**Comment by DamascenoRafael** [comment]
@renanrhoden, no ambiente de dev você pode utilizar identificação `123` e chave `123`. É um usuário de teste genérico.

**Comment by renanrhoden** [comment]
@DamascenoRafael sugestao para alterar a string "Ops! Parece que preencheu incorretamente a placa do seu carro. Verifique se a preencheu no formato "ABC-1234"" ?

**Comment by DamascenoRafael** [comment]
@renanrhoden "Ops! Parece que você preencheu incorretamente a placa do seu carro. Verifique se a preencheu no formato "ABC-1234" ou no formato Mercosul (com quatro letras e três números)."
